### ISSUE TITLE
Add pagination to posts and profiles page.

### ISSUE THREAD

**Issue by itsnitinr** [itsnitinr/driwwwle#19]
**Explanation:**
Currently, all posts page and profiles page show all the posts and profiles on a single page which leads to a very long page. Adding pagination such that only 6 posts or profiles are displayed on a single page would improve the user experience. 

**Components Responsible:**
`PostsPage.component.jsx`
`ProfilesPage.component.jsx`

**Routes:**
localhost:3000/posts
localhost:3000/profiles

**Comment by wander-igdst** [comment]
@itsnitinr Shall I work on this?

**Comment by itsnitinr** [comment]
Sure @wander-igdst

**Comment by itsnitinr** [comment]
@wander-igdst Are you working on this?
