### ISSUE TITLE
Issue with the on a new line comments

### ISSUE THREAD

**Issue by medaminefh** [itsnitinr/driwwwle#5]
When I type some comments on a new line to have some readable comments

![Screenshot from 2021-09-27 19-32-50](https://user-images.githubusercontent.com/37845480/135064918-1276a966-7830-467d-a9a0-9a3d57c5206f.png)

When I click the button this is what I get

![Screenshot from 2021-09-27 19-32-55](https://user-images.githubusercontent.com/37845480/135064927-26111d4f-20bd-4bd4-afef-fcd228cc1749.png)

**Comment by itsnitinr** [comment]
Should be fixed soon. Thanks for notifying me!

**Comment by dhruvsaxena1998** [comment]
Hey @itsnitinr, If this is not in progress can I give it a try and work on it for hacktoberfest event :)

**Comment by itsnitinr** [comment]
Alll yours @dhruvsaxena1998 😀. I had already implemented this but hadn't merged it yet. But you can still go ahead, maybe you'll have a better idea. I used the existing rich text editor package.

**Comment by dhruvsaxena1998** [comment]
Well it's the way to go, as editor has already implemented but If you do not want that much functionality for comments there's one more easy solution on how you are displaying the comment. I guess just adding this class `whitespace-pre-wrap` to paragraph tag should fix multiline issue.

**Comment by itsnitinr** [comment]
Oh wow, this solution seems simpler and good enough for the current usecase. Please go ahead with this one if it works :)
