### ISSUE TITLE
Arrows on carrousel are invisible when image is white

### ISSUE THREAD

**Issue by brunocalou** [itsnitinr/driwwwle#6]
The arrows are fully white, so when there is a white image, they seem invisible.

I think adding a light border to them would fix this issue and keep the consistency with the other site elements. 

![Captura de Tela 2021-09-29 às 14 00 33](https://user-images.githubusercontent.com/5948318/135315277-01fcf311-d824-43f9-81fd-4789b7bfc3a9.png)

**Comment by ampsteric** [comment]
hey! , would love to work on this issue for hacktoberfest, please assign it to me and add hacktoberfest tag.

**Comment by itsnitinr** [comment]
Here you go. I've added the topic to the repository.

**Comment by ampsteric** [comment]
![image](https://user-images.githubusercontent.com/56419358/135512138-b7c0a277-f5aa-4086-9fc4-b1152e857fc0.png)
i tried to implement those matching with the theme of the website , what do you think of it?

**Comment by itsnitinr** [comment]
Awesome job @ampsteric! Could you please share another screenshot without zoom? Just to see how big it would look. Also, is this a gradient?

**Comment by ampsteric** [comment]
yeah sure.
![image](https://user-images.githubusercontent.com/56419358/135564991-cbfd76e0-ec3e-404b-b68a-a94d66a1c552.png)

and yeah ,I have added gradients just to make it blend easily with the current theme of driwwwle.

**Comment by itsnitinr** [comment]
Hi @ampsteric, I think the arrows are a little bit bigger and out of position. Please check the original ones. Not sure if it'll look great on mobile view. Since I'm not using gradients anywhere, I think a solid pink shade would be better. What do you say?

Please make a pull request when you're ready and I'll make small edits (if needed). Thanks again!

**Comment by itsnitinr** [comment]
Fixed by #8
