### ISSUE TITLE
No email is sent after sign up

### ISSUE THREAD

**Issue by tommywalkie** [itsnitinr/driwwwle#7]
First of all, congrats on releasing Driwwwle.
I wanted to sign up and couldn't get the email verification link. I tried:
- Resetting my password, and I got the mail with the reset link.
- Re-signing up with the same username (_tommywalkie_), and Driwwwle told me it was already taken (so I _guess_ it worked the first time)

**Comment by itsnitinr** [comment]
Hi @tommywalkie, thanks for reporting the issue. If you're using Gmail, could you please confirm if you have received the email in the 'Promotions' or spam folder? Thanks a lot.

**Comment by tommywalkie** [comment]
@itsnitinr 'Promotions' is where I got the password reset link. Unfortunately, I still didn't find anything in spams.

**Comment by itsnitinr** [comment]
@tommywalkie Ahh that's unfortunate. Would you mind filling out the registration form again?  I'll delete the user account. Hopefully, you should get the email this time. Sorry for the inconvenience.

**Comment by tommywalkie** [comment]
@itsnitinr Well, now I got an email verification link, but I run into token related issues on the onboarding form.
> Invalid or expired token

It might be the email I was looking for in the first place, hence the error message 🤷

**Comment by itsnitinr** [comment]
Yes, that must be the old email. Did you receive it just now? Maybe you'll receive the new email in a couple of minutes. In case you don't, let me know over here. I'll manually verify your account :) Before that, please check if the second email is present inside the email thread.

**Comment by tommywalkie** [comment]
I got the email just now and could submit the onboarding form 👍 Thanks for the help @itsnitinr !
